[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "node dist/cli/index.js start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
